---
abstract: 'Perl module for providing OO methods to perl data structures.'
author:
  - 'Jason Fried <fried@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Object
no_index:
  directory:
    - inc
    - t
requires:
  Moose: 0.90
  Scalar::Util: 1.20
  namespace::autoclean: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/fried/Data-Object
version: 0.005
